// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using apiRest.Data;

#nullable disable

namespace apiRest.Migrations
{
    [DbContext(typeof(PersonalContext))]
    [Migration("20220628034225_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("apiRest.Models.Personal", b =>
                {
                    b.Property<int>("Usr_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("First_name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Last_name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Usr_name")
                        .HasColumnType("TEXT");

                    b.HasKey("Usr_id");

                    b.ToTable("Personals");
                });
#pragma warning restore 612, 618
        }
    }
}
